name: Deploy Gatus

on:
    push:
        branches:
            - main


jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
          - name: checkout code
            uses: actions/checkout@v4


          - name: Debug OIDC claims
            run: | 
             echo "Expected sub: repo:${{ github.repository }}:ref:${{ github.ref }}"


          - name: configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                role-to-assume: arn:aws:iam::192902842825:role/GitHubActions-Gatus
                aws-region: eu-west-1


          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3

          - name: Terraform Init
            working-directory: infra
            run: terraform init

          - name: Terraform Plan
            working-directory: infra
            run: terraform plan


          - name: Terraform Apply
            working-directory: infra
            run: terraform apply -auto-approve




          - name: login to ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2



          - name: Build Docker image
            run: docker build -t gatus-terraform .


          - name: Tag Docker image with commit SHA
            run: docker tag gatus-terraform:latest ${{ steps.login-ecr.outputs.registry }}/gatus-terraform:${{ github.sha }}

          - name: Push Docker image with commit SHA
            run: docker push ${{ steps.login-ecr.outputs.registry }}/gatus-terraform:${{ github.sha }}

          - name: Deploy to ECS
            run: aws ecs update-service --cluster gatus --service gatus-ecs-service --force-new-deployment
